Rewrite printf() due to -Werror=format-security
Avoid -Werror=format-security leading to: netlink/settings.c:378:2: error:
format not a string literal and no format arguments [-Werror=format-security]

Signed-off-by: Robert Scheck <robert@fedoraproject.org>
Signed-off-by: John W. Linville <linville@tuxdriver.com>