fix unused parameter warning in tg3_dump_{eeprom, regs}()
This fixes:
  external/ethtool/tg3.c:8:41: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  tg3_dump_eeprom(struct ethtool_drvinfo *info, struct ethtool_eeprom *ee)

  external/ethtool/tg3.c:27:39: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  tg3_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: I9b357d371095df4b24f2c6ec32fa3d0c99731805
Signed-off-by: John W. Linville <linville@tuxdriver.com>