fix unused parameter warning in st_{mac100, gmac}_dump_regs()
This fixes:
  external/ethtool/stmmac.c:21:49: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int st_mac100_dump_regs(struct ethtool_drvinfo *info,

  external/ethtool/stmmac.c:54:47: error: unused parameter 'info' [-Werror,-Wunused-parameter]
  int st_gmac_dump_regs(struct ethtool_drvinfo *info, struct ethtool_regs *regs)

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Change-Id: Ie72738aea1d903df4aec417cbead9e6109ee108f
Signed-off-by: John W. Linville <linville@tuxdriver.com>