ethtool: change to new sane powerpc64 kernel headers
This fixes:
  In file included from ethtool-copy.h:22:0,
                   from internal.h:32,
                   from ethtool.c:29:
  .../include/linux/types.h:32:25: error: conflicting types for '__be64'
   typedef __u64 __bitwise __be64;
                           ^
  In file included from ethtool.c:29:0:
  internal.h:23:28: note: previous declaration of '__be64' was here
   typedef unsigned long long __be64;
                              ^
  ethtool.c: In function 'do_gstats':
  ethtool.c:3166:4: error: format '%llu' expects argument of type 'long long unsigned int', but argument 5 has type '__u64' [-Werror=format=]
      stats->data[i]);
      ^
  ethtool.c: In function 'print_indir_table':
  ethtool.c:3293:9: error: format '%llu' expects argument of type 'long long unsigned int', but argument 3 has type '__u64' [-Werror=format=]
           ctx->devname, ring_count->data);
           ^

$ gcc -dM -E - <<< "" | egrep -i 'power|ppc|arm|aarch|x86|86|amd'

.#define __x86_64 1
.#define __amd64 1
.#define __x86_64__ 1
.#define __amd64__ 1

.#define _ARCH_PPCGR 1
.#define __PPC64__ 1
.#define _ARCH_PPC 1
.#define __powerpc64__ 1
.#define __PPC__ 1
.#define __powerpc__ 1
.#define _ARCH_PPC64 1

.#define __AARCH64_CMODEL_SMALL__ 1
.#define __aarch64__ 1
.#define __AARCH64EL__ 1
.#define __ARM_NEON 1

Signed-off-by: Maciej Żenczykowski <maze@google.com>
Signed-off-by: John W. Linville <linville@tuxdriver.com>